# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: musescore downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Mucescore url'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        echo -e 'str=$(npx msdl|grep "File URL:"|cut -d\\':\\' -f 1)\ncurl -o f.zip $str\nunzip f.zip -d ./score'>0.sh
        chmod +x 0.sh
        cat 0.sh
        sudo apt-get install expect
        echo -e '#!/usr/bin/expect\\nspawn ./0.sh\\nexpect \"usually Ctrl+Shift+V to paste\"\\nsend \"${{ github.event.inputs.url }}\\\\n\"\\nexpect \"Continue? (Y/n)\"\\nsend \"Y\\\\n\"\\nexpect off'>1.sh"
        chmod +x 1.sh
        cat 1.sh
        ./1.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
       # Artifact name
        name: score
        # Directory containing files to upload
        path: "./score/"
