# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: musescore downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Mucescore url'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: printf "${{ github.event.inputs.url }}\nY\n" |npx msdl
