name: 'Download From spotify list'
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Spotify Playlist url'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt install ffmpeg
        pip3 install spotdl
    - name: Download songs
      run: |
        mkdir downloaded
        cd downloaded
        spotdl --playlist ${{ github.event.inputs.url }} --write-to=list.txt
        spotdl --list list.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: songs
        path: "./downloaded/"
