# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Youtube downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Youtube url'
        required: true

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        repository: ytdl-org/youtube-dl
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo -H pip install --upgrade youtube-dl
    - name: Download project
      run: |
        python ./youtube-dl --verbose -o 'dl/%(title).%(ext)' ${{ github.event.inputs.url }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: songs
        path: "./dl/"
